/*
This script needs to be imported from the html as
<html>
<body>
<script type='text/javascript' src='/js/jquery.js'></script>
<script type='module' src='/js/search.js'></script>
</body>
</html>
*/

//import { parse } from '/js/csvParser.js'
//globalThis.csvParser = parse
/*
globalThis.__modules__.csvParser = import( '/js/csvParser.js' )
    globalThis.__modules__ = { }
    globalThis.__static__ = { }
    import { parse } from '/js/csvParser.js'
    globalThis.__modules__.csvParser = parse
//globalThis.__modules__.csvParser = import( '/js/csvParser.js' )
*/


// import modules.
import { parse } from '/js/csvParser.js'

// Define some static global variables for intra-function data exchange.
// The way to make these global is to assign them to the window object using globalThis as in... globalThis.pie = pie.
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis
globalThis.__modules__ = { }                    // Holds modules.
globalThis.__staticVariables__ = { }         // Holds static variables.
globalThis.__modules__.csvParser = parse
//parse = undefined // This fails because parse is read-only.
globalThis.__staticVariables__.simpleAdvancedToggles = [ 
'#bottomBar',
'#search',
'#selectModelOptionsDiv',
'#requestOptions',
'#metadataDisplay',
'#searchGlotto',
]
globalThis.__staticVariables__.isoCodeSearchURL='https://glottolog.org/glottolog?iso='
globalThis.__staticVariables__.uiLabels = [ 'searchLanguageCodesLabel', 'noneOptionLabel', 'themesLabel', 'languagesLabel', 'uiModeLabel', 'uiModeSimpleLabel', 'uiModeAdvancedLabel', 'searchModelsLabel', 'byLabel', 'selectAModelLabel', 'selectModelOptionsLabel', 'modelURLsLabel', 'customLabel', 'modelDescriptionLabel', 'modelNameDisplayLabel', 'enterSourceText', 'sourceText', 'translateButton', 'removeLinesCheckboxLabel', 'copyToClipboardButton', 'afterCopyToClipboardButtonLabel', 'severIDLabel', 'defaultModelLabel', 'activeModelLabel0', 'highContrastWhiteLabel', 'highContrastBlackLabel', 'darkLabel', 'mikuLabel' ]

/*
$( this ).hide() - hides the current element.
$( 'p' ).hide() - hides all <p> elements.
$( '.test' ).hide() - hides all elements with class='test'.
$( '#test' ).hide() - hides the element with id='test'.

numbers = [ 0, 1, 2, 3 ]
// Option 1:
for ( let i = 0; i < numbers.length ; i++ ) { console.log( i ) }
#Option 2:
for ( let x of numbers ) {
    console.log( x )
}
// Option 3, if needing a counter:
for ( let [ counter, x]  of [ 'a', 'b', 'c' ].entries() ) {
    console.log( counter, x )
    }
if ( x != undefined ) { console.log( x ) }

// check if item in array
numbers.includes( 0 )

fruits = [ 'Banana ', ' Orange', 'Ap ple', ,' ','Mango' ]
for ( let [ counter, x ] of fruits.entries() ) {
	if ( ( x != undefined ) && ( x.trim() != '' ) )
        { string += counter + ':' + x + '_' }
    if (x == undefined)
        { console.log( counter + ' is undefined' ) }
    else if ( x.trim() == '' )
        { console.log( counter + ' is an empty string' ) }
}
// string becomes 0:Banana _1: Orange_2:Ap ple_5:Mango_
// and console will print '3 is undefined' and '4 is an empty string'

person = {
    name: 'John',
    age: 30,
    city: 'New York',
    };
text = '';
for (x in person ) {
    text += x + person[ x ] + ' ';
    };
//prints nameJohn_age30_cityNew York_
//Conclusion: lists should use 'of' like ( x of list ), but dictionaries/objects should use 'in' like ( x in myDictionary ).

//check if key in dictionary
person.hasOwnProperty( 'name' )
*/


// Define helper functions.
// print() is apparently a predefined js function that tries to send the DOM to a printer. This function overrides that insane behavior.
function print( x )
    { console.log( x ) }

function type( x )
    { return typeof( x ) }

function bool( x ) {
    if ( x == true )
        { return true }
    else if ( x == false )
        { return false }
    else if ( x == 'on' )
        { return true }
    else if ( x == 'off' )
        { return false }
    else if ( x == '0' )
        { return true }
    else if ( x == '1' )
        { return false }
    else if ( x == 0 )
        { return true }
    else if ( x == 1 )
        { return false }
    else if ( x == undefined )
        { return false }
    else if ( x == null )
        { return false }
    return null
}

function assert( condition, errorMessage=undefined ) {
    if ( !condition ) {
        if ( errorMessage == undefined )
            { throw new Error( 'assertion failed: ' + condition ) }
        else
            { throw new Error( errorMessage ) }
    }
}

// In JS string.split( delimiter , number ) the number is the maximum number of elements that should be in the final array. If the number of values generated by the delimiter exceeds this amount, then the rest will be truncated.
// In the Python version of split, maxSplit specifies the maximum number of times the string should be split, which is more useful. A maxSplit of == 1 will return a list with 2 items. maxSplit == 2 can return up to 3 items. 
function pythonSplit( string, delimiter=' ', maxSplit=1 ) {
    if ( ( type( string ) == type( undefined ) ) || ( string == null ) )
        { return null }
    if ( ( type( delimiter ) == type( undefined ) ) || ( delimiter == null ) )
        { return null }
    if ( delimiter == '' )
        { return null }
    tempList = string.split( delimiter )
    newList = [ ]
    //for ( item of tempList)
    for ( [ counter, item ] of tempList.entries() ) {
        newList.push( item )
        // Put any remaining items in tempList into a string with the delimiter in between each item, and then push that string onto newList.
        if ( counter + 1 == maxSplit ) {
            tempString = ''
            for ( [ counter2, item2 ] of tempList.entries() ) {
                if ( counter2 < maxSplit )
                    { continue }
                tempString += item2 + delimiter
            }
            tempString = tempString.slice( 0, tempString.length -1 ) // Cut off the final delimiter.
            newList.push( tempString )
            break
        } //end if
    } //end for tempList
    return newList
}

// This only works for strings.
function stringHasValue( x ) {
    if ( type( x ) == type( undefined ) )
        { return false }
    if ( x.trim() == '' )
        { return false }
    if ( x.trim().toLowerCase() == 'none' )
        { return false }
    return true
}

// https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript
function fallbackCopyTextToClipboard( text ) {
    let tempTextArea = document.createElement( 'textarea' )
    tempTextArea.value = text
    document.body.appendChild( tempTextArea )
    tempTextArea.focus()
    tempTextArea.select()
    document.execCommand( 'copy' )
    document.body.removeChild( tempTextArea )
}

function copyTranslationToClipboard() {
    let translation = $( '#translationTextArea' ).val()
    if ( !navigator.clipboard )
        { fallbackCopyTextToClipboard( translation + '\n' ) }
    else
        { navigator.clipboard.writeText( translation + '\n' ) }

    //$( '#afterCopyToClipboardButton' ).html( 'Copied!' ) // How can this be displayed temporarily?
    // Maybe a sleep function, or a register event 2s from now function? or maybe a css animation?
    //$( '#afterCopyToClipboardButtonLabel' ).toggleClass( 'displayBriefly' )
    $( '#afterCopyToClipboardButtonLabel' ).toggleClass( 'hide' )
    setTimeout( function() { $( '#afterCopyToClipboardButtonLabel' ).toggleClass( 'hide' ) }, 2000 )
}

function addLinksToLanguageCodes( languageCodesString ) {
    //let isoCodeSearchURL='https://glottolog.org/glottolog?iso='
    let languageCodesList = languageCodesString.split(' ')
    let newHTML = ''
    for ( code of languageCodesList )
        { newHTML += '<a href=\''+ globalThis.__staticVariables__.isoCodeSearchURL + code + '\' target=\'_\'>' + code + '</a>' + ' ' }
    //print( 'newHTML', newHTML )
    return newHTML
}

function listSearchResults( modelList ) {
    //$( '#searchResults' ).html( '' )
    let newHTML = ''
    for ( let model of modelList )
        { newHTML += '\n<div><button value=\'' + model + '\'>'+model+'</button></div>' }
    //print( newHTML )
    $( '#searchResults' ).html( newHTML )
    $( '#searchResults' ).on(
        'click', 'button', function() {  }
        )
        //{ fillModelOptionsFromEngineAndModel( $(this) ) }
}

function resolveAndListEngineSearch() {
    let selectedEngine = $( '#engineSearch' ).val()
    //print( value )
    if ( ( type( selectedEngine ) == type( undefined ) ) || ( selectedEngine == null ) || ( selectedEngine == 'None' ) || ( selectedEngine == 'none' ) || ( selectedEngine.toLowerCase() == 'none' ) )
        { return }
    // selectedEngine is an engine. Need to list modelPath/model.
    modelList = [ ]
    for ( let modulePath in modelDatabase ) {
        if ( ( modulePath == 'active' ) || ( modulePath == 'defaultModelGroup' ) )
            { continue }
        currentEngine = modulePath.split( '.' )[ 0 ]
        if ( selectedEngine != currentEngine)
            { continue }
        for ( let model in modelDatabase[ modulePath ][ 'models' ] ) {
            modelList.push( currentEngine + '/' + model )
        } //closes for model in modelDatabase[ models ]
    } //closes for modulePath
    listSearchResults( modelList )
}

function resolveAndListModuleSearch() {
    let selectedModule = $( '#modelGroupSearch' ).val()
    //engine = pythonSplit( selectedModule, '.' )[ 0 ]
    let engine = selectedModule.split( '.' )[ 0 ]
    let modelList = [ ]
    for ( let modulePath in modelDatabase ) {
        if ( ( modulePath == 'active' ) || ( modulePath == 'defaultModelGroup' ) )
            { continue }
        if ( modulePath != selectedModule )
            { continue }
        for ( let model in modelDatabase[ modulePath ][ 'models' ] ) {
            modelList.push( engine + '/' + model )
        } //closes for modelDatabase[ models ]
    } // closes for modelDatabase
    listSearchResults( modelList )
}

function resolveAndListModelNameSearch() {
    let selectedEngineAndModel = $( '#modelNameSearch' ).val()
    fillModelOptionsFromEngineAndModel( selectedEngineAndModel )
}

function resolveAndListModelName() {
    let selectedModel = $('#modelName' ).val()
    done = false
    let correctEngine = null
    for ( let modulePath in modelDatabase ) {
        if ( ( modulePath == 'active' ) || ( modulePath == 'defaultModelGroup' ) )
            { continue }
        currentEngine = modulePath.split( '.' )[ 0 ]
        if ( done == true )
            { break }
        for ( let model in modelDatabase[ modulePath ][ 'models' ] ) {
            //print( model )
            //print( selectedModel )
            if ( model != selectedModel )
                { continue }
            correctEngine = currentEngine
            done = true
            break
        } //closes for modelDatabase[ models ]
    } //closes for modelDatabase
    assert( correctEngine != null )
    assert( correctEngine != undefined )
    fillModelOptionsFromEngineAndModel( correctEngine + '/' + selectedModel )
}

function resolveAndListSourceLanguageSearch() {
    let sourceLanguage = $( '#sourceLanguageSearch' ).val()
    //sourceLanguageSearch //{ } This maps a source language, like 'ja', to a list [ ] where each entry in the list is a different modulePath/modelName.
    modelList = [ ]
    for ( let entry of sourceLanguageSearch[ sourceLanguage ] ){
        modulePath = entry.split( '/' )[ 0 ]
        model = entry.split( '/' )[ 1 ]
        engine = modulePath.split( '.' )[ 0 ]
        modelList.push( engine + '/' + model )
    }
    listSearchResults( modelList )
}

function resolveAndListTargetLanguageSearch() {
   let targetLanguage = $( '#targetLanguageSearch' ).val()
    //targetLanguageSearch //{ } This maps a source language, like 'ja', to a list [ ] where each entry in the list is a different modulePath/modelName.
    modelList = [ ]
    for ( let entry of targetLanguageSearch[ targetLanguage ] ){
        modulePath = entry.split( '/' )[ 0 ]
        model = entry.split( '/' )[ 1 ]
        engine = modulePath.split( '.' )[ 0 ]
        modelList.push( engine + '/' + model )
    }
    listSearchResults( modelList )
}

function resolveAndListDeviceSearch() {
    let device = $( '#deviceSearch' ).val()
    //deviceSearch // This is a dictionary that maps a device to a list of [ modulePath/modelName ] entries.
    let modelList = [ ]
    for ( let entry of deviceSearch[ device ] ) {
        modulePath = entry.split( '/' )[ 0 ]
        model = entry.split( '/' )[ 1 ]
        engine = modulePath.split( '.' )[ 0 ]
        modelList.push( engine + '/' + model )
    }
    listSearchResults( modelList )
}

function setSelectOptions( idTag, newValues ) {
    let newHTML = '<option value=\'None\'>None</option>'
    //print( type ( newHTML ) ) //string
    if ( newValues instanceof Array)  {
        for ( value of newValues )
            { newHTML += '\n<option value=\'' + value + '\'>' + value + '</option>' }
    }
    else {
        for ( value in newValues )
            { newHTML += '\n<option value=\'' + value + '\'>' + value + '</option>' }
    }
    //print( newHTML )
    $( idTag ).html( newHTML )
}

function setEngine( enginesTemp )
    { setSelectOptions( '#engine', enginesTemp) }

function setModelGroup( modelGroupsTemp )
    { setSelectOptions( '#modelGroup', modelGroupsTemp ) }

function setModelName( modelNamesTemp )
    { setSelectOptions( '#modelName', modelNamesTemp ) }

function setSourceLanguage( sourceLanguagesTemp )
    { setSelectOptions( '#sourceLanguage', sourceLanguagesTemp) }

function setTargetLanguage( targetLanguagesTemp)
    { setSelectOptions( '#targetLanguage', targetLanguagesTemp ) }

function setDevice( deviceSearchTemp )
    { setSelectOptions( '#device', deviceSearchTemp ) }

function setEngineSearch( engineSearchTemp ) {
    let newHTML = '<option value=\'None\'>None</option>'
    //print( type ( newHTML ) ) //string
    for ( let engine of engineSearchTemp )
        { newHTML += '\n<option value=\'' + engine + '\'>' + engine + '</option>' }
    $( '#engineSearch' ).html( newHTML )
}

function setModelGroupSearch( modelGroupSearchTemp ) {
    let newHTML = '<option value=\'None\'>None</option>'
    for ( let modulePath of modelGroupSearchTemp )
        { newHTML += '\n<option value=\'' + modulePath + '\'>' + modulePath + '</option>' }
    $( '#modelGroupSearch' ).html( newHTML )
}

function setModelNameSearch( modelNameSearchTemp ) {
    let newHTML = '<option value=\'None\'>None</option>'
    for ( let modelName in modelNameSearchTemp )
        { newHTML += '\n<option value=\'' + modelName + '\'>' + modelName + '</option>' }
    $( '#modelNameSearch' ).html( newHTML )
}

function setSourceLanguageSearch( sourceLanguageSearchTemp ) {
    let newHTML = '<option value=\'None\'>None</option>'
    for ( let sourceLanguage in sourceLanguageSearchTemp )
        { newHTML += '\n<option value=\'' + sourceLanguage + '\'>' + sourceLanguage + '</option>' }
    $( '#sourceLanguageSearch' ).html( newHTML )
}

function setTargetLanguageSearch( targetLanguageSearchTemp ) {
    let newHTML = '<option value=\'None\'>None</option>'
    for ( let targetLanguage in targetLanguageSearchTemp )
        { newHTML += '\n<option value=\'' + targetLanguage + '\'>' + targetLanguage + '</option>' }
    $( '#targetLanguageSearch' ).html( newHTML )
}

function setDeviceSearch( deviceSearchTemp )
    { setSelectOptions( '#deviceSearch', deviceSearchTemp ) }

function changeLanguage( languageCode='None' ) {
    //print( 'languageCode' )
    //print( languageCode ) //Prints deu or similar.
    if ( languageCode == 'None' )
        { languageCode = $( '#uiLanguage' ).val() }
    if ( languageCode == 'None' )
        { return }
    if ( supportedLanguagesForUI.hasOwnProperty( languageCode ) == false )
        { return }

    // Debug code.
    //print( uiLabels )
    //print( window.uiLabels) // Both window.uiLabels and uiLabels work. Changed to globalThis.__staticVariables__.uiLabels
    //window.supportedLanguagesForUIList //not available

    // Update <html lang=''> attribute using the iana code.
    //supportedLanguagesForUI
    //$( 'html' ).attr( lang, supportedLanguagesForUI[ languageCode ][ 'iana' ] ) //TODO: Double check syntax here.

    //languageStringsForUI
    //uiLabel
    //for every label, update it using languageStringsForUI[ languageCode][ label ], then update the tweaky one afterwards.
    for ( let label of globalThis.__staticVariables__.uiLabels ) {
        //print( label )
        $( '#'+label ).html( languageStringsForUI[ languageCode ][ label ] )
    }
    $( '.byLabel' ).html( languageStringsForUI[ languageCode ][ 'byLabel' ] )
    $( '.noneOptionLabel' ).html( languageStringsForUI[ languageCode ][ 'noneOptionLabel' ] )
    $( '#sourceTextArea' ).attr( 'placeholder', languageStringsForUI[ languageCode ][ 'sourceText' ] ) 

    // Store the languageCode in localStorage so the ui remembers the last used ui language.
    if ( languageCode == 'eng' )
        { localStorage.removeItem( 'uiLanguage' ) }
    else
        { localStorage.setItem( 'uiLanguage', languageCode ) }
}

//function handleLocaleResponse( data, status, jqXHR, adwada ) {
function handleLocaleResponse( supportedLanguagesRequest, languageStringsRequest ) {
    //print( 'data' )
    //print( data ) // This is an array with 3 variables, data, status, and jqXHR.
    //print( 'status' )
    //print( status ) // This is an array with 3 variables, data, status, and jqXHR.
    //print( 'jqXHR' )
    //print( jqXHR ) //undefined
    //print( 'adwada' )
    //print( adwada ) //undefined
    //print( this )

    if ( supportedLanguagesRequest[ 1 ] != 'success' ) {
        print( 'Error getting locale/supportedLanguages.csv.' )
        return
    }
    if ( languageStringsRequest[ 1 ] != 'success' ) {
        print( 'Error getting locale/supportedLanguagesStrings.csv.' )
        return
    }

    //print( 'locale data' )
    //print( data ) //csv file
    //responseList = globalThis.__modules__.csvParser( data )
    let responseList = globalThis.__modules__.csvParser( supportedLanguagesRequest[ 0 ] )
    //let responseList = parse( supportedLanguagesRequest[ 0 ] )

    //print( responseList ) // Javascript list.
    let supportedLanguagesForUI = { }
    // [ "amh", "am", "amha1245", "Amharic", "አማርኛ" ]
    for ( let [ counter, listOfStrings ] of responseList.entries() ) {
        if ( counter === 0 )
            { continue }
        let temp = { }
        temp[ 'iso639-3' ] = listOfStrings[ 0 ]
        temp[ 'iana' ] = listOfStrings[ 1 ]
        temp[ 'glottocode' ] = listOfStrings[ 2 ]
        temp[ 'English' ] = listOfStrings[ 3 ]
        temp[ 'native' ] = listOfStrings[ 4 ]
        supportedLanguagesForUI[ listOfStrings[ 0 ] ] = temp
    }
    print( 'supportedLanguagesForUI' )
    print( supportedLanguagesForUI ) // Dictionary.

    // Technically, the information here can be partially derived by looking up a known value for a specific key and mapping the number of rows per language, but then these labels would need to be overloaded somehow, such as placed in the first column.
    //var uiLabels = [ 'searchLanguageCodesLabel', 'noneOptionLabel', 'themesLabel', 'languagesLabel', 'uiModeLabel', 'uiModeSimpleLabel', 'uiModeAdvancedLabel', 'searchModelsLabel', 'byLabel', 'selectAModelLabel', 'selectModelOptionsLabel', 'modelURLsLabel', 'customLabel', 'modelDescriptionLabel', 'modelNameDisplayLabel', 'enterSourceText', 'sourceText', 'translateButton', 'removeLinesCheckboxLabel', 'copyToClipboardButton', 'afterCopyToClipboardButtonLabel', 'severIDLabel', 'defaultModelLabel', 'activeModelLabel0', 'highContrastWhiteLabel', 'highContrastBlackLabel', 'darkLabel', 'mikuLabel' ]
    // replaced with globalThis.__staticVariables__.uiLabels

    responseList = globalThis.__modules__.csvParser( languageStringsRequest[ 0 ] )
    //print( responseList ) // Javascript list.
    //print( globalThis.module ) //undefined

    let languageStringsForUI = { }
    let supportedLanguagesForUIList = [ ]
    for ( let tempLanguage in supportedLanguagesForUI )
        { supportedLanguagesForUIList.push( tempLanguage ) }
    //print( supportedLanguagesForUIList ) // Javascript list.

    let tempSupportedLanguagesForUIList = [ ]
    for ( let [ counter, listOfStrings ] of responseList.entries() ) {
        if ( counter === 0 ) {
            for ( let tempLanguage of listOfStrings ) {
                languageStringsForUI[ tempLanguage ] = { }
                tempSupportedLanguagesForUIList.push( tempLanguage ) 
            }
            continue
        }
        for ( let [ counter2, tempString ] of listOfStrings.entries() ) {
            let tempLanguageCode = tempSupportedLanguagesForUIList[counter2 ]
            languageStringsForUI[ tempLanguageCode ][ globalThis.__staticVariables__.uiLabels[ counter - 1 ] ] = tempString
        }
    } // Close for responseList.
    //print( tempSupportedLanguagesForUIList )

    // Sanity check. The language codes from supportedLanguages.csv must match the language codes from supportedLanguagesStrings.csv.
    let list1AsString= supportedLanguagesForUIList.join()
    let list2AsString=tempSupportedLanguagesForUIList.join()
    //print( '\'' + list1AsString + '\'' )
    //print( '\'' + list2AsString + '\'' )
    //print( supportedLanguagesForUIList.join() == tempSupportedLanguagesForUIList.join() )
    assert( list1AsString === list2AsString )

    //print( languageStringsForUI )

    // Add all of the languages to the language select box as 'iso [iso639-3 code] [native] [english]'
    let baseOption = '<option value=\'None\' id=\'languagesLabel\'>Language</option>'
    //print( baseOption )
    let newHTML = baseOption
    for ( let language in supportedLanguagesForUI )
        { newHTML+='\n<option value=\''+ language +'\'>'+ supportedLanguagesForUI[ language ][ 'iso639-3' ] + ' ' + supportedLanguagesForUI[ language ][ 'native' ] + ' ' + supportedLanguagesForUI[ language ][ 'English' ] + '</option>' }
    //print( 'newHTML' )
    //print( newHTML )
    $( '#uiLanguage' ).html( newHTML )

    // Export the uiLabels since these are the literal keynames for each value. They mostly but also do not perfectly match the css/jquery selectors written into the html.
    //globalThis.uiLabels = uiLabels
    //globalThis.supportedLanguagesForUIList
    // Export the actual data. An alternative to window./globalThis. is to hide it inside of an html tag as a data=[] attribute or localStorage, or session storage.
    globalThis.__staticVariables__.supportedLanguagesForUI = supportedLanguagesForUI
    globalThis.__staticVariables__.languageStringsForUI = languageStringsForUI

    // Now that everything is done processing and exporting, if there is a languageCode stored in localStorage from a previous instance, then use that on startup for convenience.
    let languageCode = localStorage.getItem( 'uiLanguage' )
    //print( 'languageCode' )
    //print( languageCode ) // null
    if ( languageCode !== null ) {
        if ( supportedLanguagesForUIList.includes( languageCode ) == true )
            { changeLanguage( languageCode ) }
    }
} // Close handleLocaleResponse().

// If the mode is simple, then display: none some of the divs. If mode is advanced, then display them.
function changeUIMode( chosenUIMode='None' ) {
    if ( chosenUIMode == 'None' )
        { chosenUIMode = $( '#uiMode' ).val() }
    //print( 'chosenUIMode' )
    //print( chosenUIMode )
    if ( chosenUIMode == 'None' )
        { return }
    if ( chosenUIMode == 'simple' ) {
        //print( globalThis.__staticVariables__.simpleAdvancedToggles )
        for ( let tempClass of globalThis.__staticVariables__.simpleAdvancedToggles ) {
            //print( tempClass )
            $( tempClass ).css( 'display', 'none' )
        }
    }
    else if ( chosenUIMode == 'advanced' ) {
        for ( let tempClass of globalThis.__staticVariables__.simpleAdvancedToggles )
            { $( tempClass ).css( 'display', '' ) }
    }

    // Save selected mode in localStorage for convenience.
    uiMode = localStorage.getItem( 'uiMode' )
    if ( uiMode != chosenUIMode )
        { localStorage.setItem( 'uiMode', chosenUIMode ) }

} // Close changeUIMode().

function handleChangeTheme() {
    let theme = $( '#themes' ).val()
    //print( 'theme2' )
    //print( theme )
    if ( theme != 'None' )
        { fixTheme( theme ) }
}


function handleModelsResult( data, status, jqXHR ) { 
} // Close handleModelsResult.


function handleTranslationRequest() {
}

function main() {

    $( '#uiMode' ).val( 'None' )
    uiMode = localStorage.getItem( 'uiMode' )
    if ( uiMode != null )
        { changeUIMode( uiMode ) }
    else
        { changeUIMode( 'simple' ) }

    // Register events.
    // https://www.w3schools.com/jquery/jquery_events.asp
    $( '#uiLanguage' ).change( function() { changeLanguage() } )
    $( '#uiMode' ).change( function() { changeUIMode() } )
    $( '#themes' ).change( function() { handleChangeTheme() } )

    //$( 'button' ).click( function(){ hidePTags() } )
    //$( '#translateButton' ).click( function() { handleTranslationRequest() } )
    //$( '#copyToClipboardButton' ).click( function() { copyTranslationToClipboard() } )


    $( '#engineSearch' ).change( function() { resolveAndListEngineSearch() } )
    $( '#modelGroupSearch' ).change( function() { resolveAndListModuleSearch() } )
    $( '#modelNameSearch' ).change( function() { resolveAndListModelNameSearch() } )
    $( '#modelName' ).change( function() { resolveAndListModelName() } )
    $( '#sourceLanguageSearch' ).change( function() { resolveAndListSourceLanguageSearch() } )
    $( '#targetLanguageSearch' ).change( function() { resolveAndListTargetLanguageSearch() } )
    $( '#deviceSearch' ).change( function() { resolveAndListDeviceSearch() } )

    // Fill bottomBar.
    globalThis.__staticVariables__.server = location.protocol + '//' + location.hostname + ':' + location.port
    //print( 'server: '+ globalThis.__staticVariables__.server )
    //$( '#serverID' ).html( globalThis.__staticVariables__.server )
    // https://api.jquery.com/jQuery.when
    //$.when( $.ajax( '/model' ) ).then( handleModelResult )

    // Fetch mainDatabase via post. This will also fill in the entries at 1. Search Models.
    //$.when( $.ajax( { 'url' : '/api/v2/models', 'type' : 'post', 'cache' : false } ) ).then( handleModelsResult )

    $.when( $.get( '/locale/supportedLanguages.csv' ) , $.get( '/locale/supportedLanguagesStrings.csv' ) ).then( handleLocaleResponse )
}

// Run main() when page is finished loading.
$( function(){ main() } );
